path=(
    ~/usr/bin
    ~/conf/bin
    ~/.local/bin
    ~/.cargo/bin
    ~/go/bin
    /usr/local/go/bin
    /opt/homebrew/opt/libpq/bin
    /opt/homebrew/opt/openjdk/bin
    /opt/homebrew/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    '/Applications/Visual Studio Code.app/Contents/Resources/app/bin'
    /Applications/Postgres.app/Contents/Versions/15/bin/
)

# TODO: Build env in Rust, and source the Rust program's output here, rather
# than doing string manipulation, variable existence checks, etc. directly in
# shell script.

# Per suggestions from brew install libpq; see: bin/install-psql.zsh
export LDFLAGS="${LDFLAGS:+$LDFLAGS }-L/opt/homebrew/opt/libpq/lib"
export CPPFLAGS="${CPPFLAGS:+$CPPFLAGS }-I/opt/homebrew/opt/libpq/include"
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH:+$PKG_CONFIG_PATH:}/opt/homebrew/opt/libpq/lib/pkgconfig"

# export CPPFLAGS="${CPPFLAGS:+$CPPFLAGS }-I/opt/homebrew/opt/openjdk/include"
export DISABLE_MAGIC_FUNCTIONS=true # Stop oh-my-zsh from being too clever.
export EDITOR='code --wait'
export FZF_DEFAULT_COMMAND='fdfind --type=f'
export LS_COLORS='di=01;36'
export PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$HOME/git/py-kart"
export PYTHONSTARTUP=~/conf/etc/pythonrc.py
export READNULLCMD=$PAGER
export RIPGREP_CONFIG_PATH=~/conf/etc/ripgreprc
export ZSH=~/.oh-my-zsh

export LESS='-FRX -j5'
export PAGER=less

# Based on 'brew shellenv' output.
export HOMEBREW_PREFIX='/usr/local'
export HOMEBREW_CELLAR='/usr/local/Cellar'
export HOMEBREW_REPOSITORY='/usr/local/Homebrew'
export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}"
export INFOPATH="/usr/local/share/info:${INFOPATH:-}"

# See 'man brew'.
export HOMEBREW_NO_ENV_HINTS=1       # Make brew upgrade a little quieter.
export HOMEBREW_NO_INSTALL_CLEANUP=1 # Don't run brew cleanup automatically.

# Required by diesel.
export PQ_LIB_DIR="$(brew --prefix libpq)/lib"

# Pyright yells that you should set PYRIGHT_PYTHON_FORCE_VERSION=latest, even if
# you've set that variable to a specific version.  But, latest is often buggy.
# The only rationale Pyright seems to respect is consistency with Pylance.
export PYRIGHT_PYTHON_FORCE_VERSION=1.1.371
export PYRIGHT_PYTHON_PYLANCE_VERSION=v2024.7.1

for conf_module in ~/git/conf-*(N); do
    if [ -r $conf_module/etc/zprofile ]; then
        source $conf_module/etc/zprofile
    fi
done
