# TODO: Build env in Rust, and source the Rust program's output here, rather
#  than doing string manipulation, variable existence checks, etc. directly in
#  shell script.

alias log="echo -n conf:"

log 'Loading primary...'
local start_time=$(~/conf/prj/target/release/log-profile)

path=(
    ~/usr/bin
    ~/conf/bin
    ~/.local/bin
    ~/.cargo/bin
    ~/go/bin
    /usr/local/go/bin
    /opt/homebrew/opt/libpq/bin
    /opt/homebrew/opt/openjdk/bin
    /opt/homebrew/bin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Library/Developer/CommandLineTools/usr/bin
    '/Applications/Visual Studio Code.app/Contents/Resources/app/bin'
)

# Per suggestions from brew install libpq; see: bin/install-psql.zsh
export LDFLAGS="${LDFLAGS:+$LDFLAGS }-L/opt/homebrew/opt/libpq/lib"
export CPPFLAGS="${CPPFLAGS:+$CPPFLAGS }-I/opt/homebrew/opt/libpq/include"
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH:+$PKG_CONFIG_PATH:}/opt/homebrew/opt/libpq/lib/pkgconfig"

# Workaround for RocksDB package from crates.io.
export DYLD_LIBRARY_PATH=/Library/Developer/CommandLineTools/usr/lib

export GITUP_TRUNKS=dev,main,master

# export CPPFLAGS="${CPPFLAGS:+$CPPFLAGS }-I/opt/homebrew/opt/openjdk/include"
export DISABLE_MAGIC_FUNCTIONS=true # Stop oh-my-zsh from being too clever.
export FZF_DEFAULT_COMMAND='fdfind --type=f'
export LS_COLORS='di=01;36'
export PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$HOME/git/py-kart"
export PYTHONSTARTUP=~/conf/etc/pythonrc.py
export READNULLCMD=$PAGER
export RIPGREP_CONFIG_PATH=~/conf/etc/ripgreprc
export ZSH=~/.oh-my-zsh

export LESS='-FRX -j5'
export PAGER=less

if [[ -v CURSOR_TRACE_ID ]]; then
    export EDITOR='cursor --wait'
elif [[ "$TERM_PROGRAM" == vscode ]]; then
    export EDITOR='code --wait'
elif [[ -v EDITOR ]]; then
    ;
else
    export EDITOR='hx'
fi

# Based on 'brew shellenv' output.
export HOMEBREW_PREFIX='/usr/local'
export HOMEBREW_CELLAR='/usr/local/Cellar'
export HOMEBREW_REPOSITORY='/usr/local/Homebrew'
export MANPATH="/usr/local/share/man${MANPATH+:$MANPATH}"
export INFOPATH="/usr/local/share/info:${INFOPATH:-}"

# See 'man brew'.
export HOMEBREW_NO_ENV_HINTS=1       # Make brew upgrade a little quieter.
export HOMEBREW_NO_INSTALL_CLEANUP=1 # Don't run brew cleanup automatically.

# Required by diesel.
export PQ_LIB_DIR="$(brew --prefix libpq)/lib"

# Pyright yells that you should set PYRIGHT_PYTHON_FORCE_VERSION=latest, even if
# you've set that variable to a specific version.  But, latest is often buggy.
# The only rationale Pyright seems to respect is consistency with Pylance.
export PYRIGHT_PYTHON_FORCE_VERSION=1.1.371
export PYRIGHT_PYTHON_PYLANCE_VERSION=v2024.7.1

export JUMP_PREFIXES=~/conf/etc/jump

~/conf/prj/target/release/log-profile $start_time
for conf_module in ~/git/conf-*(N); do
    if [ -r $conf_module/etc/zprofile ]; then
        log "Loading ${conf_module#*/conf-}..."
        local start_time=$(~/conf/prj/target/release/log-profile)
        source $conf_module/etc/zprofile
        ~/conf/prj/target/release/log-profile $start_time
    fi
done
