[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "oxlint"]
formatter = { command = "oxfmt", args = ["--stdin-filepath=file.ts"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "oxlint"]
formatter = { command = "oxfmt", args = ["--stdin-filepath=file.tsx"] }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "oxlint"]
formatter = { command = "oxfmt", args = ["--stdin-filepath=file.js"] }

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "oxlint"]
formatter = { command = "oxfmt", args = ["--stdin-filepath=file.jsx"] }

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
formatter = { command = "oxfmt", args = ["--stdin-filepath=file.json"] }

# Disable emmet-ls. Useful when writing code within script tags.
#
# [[language]]
# name = "html"
# language-servers = ["vscode-html-language-server"]
